//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 03:50:24 PM EET 
//


package preprod.qa.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the preprod.qa.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: preprod.qa.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFreeSlotsResponse }
     * 
     */
    public GetFreeSlotsResponse createGetFreeSlotsResponse() {
        return new GetFreeSlotsResponse();
    }

    /**
     * Create an instance of {@link AddBookingResponse }
     * 
     */
    public AddBookingResponse createAddBookingResponse() {
        return new AddBookingResponse();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link GetDoctorsBySpecializationRequest }
     * 
     */
    public GetDoctorsBySpecializationRequest createGetDoctorsBySpecializationRequest() {
        return new GetDoctorsBySpecializationRequest();
    }

    /**
     * Create an instance of {@link AddBookingRequest }
     * 
     */
    public AddBookingRequest createAddBookingRequest() {
        return new AddBookingRequest();
    }

    /**
     * Create an instance of {@link GetFreeSlotsRequest }
     * 
     */
    public GetFreeSlotsRequest createGetFreeSlotsRequest() {
        return new GetFreeSlotsRequest();
    }

    /**
     * Create an instance of {@link CloseBookingResponse }
     * 
     */
    public CloseBookingResponse createCloseBookingResponse() {
        return new CloseBookingResponse();
    }

    /**
     * Create an instance of {@link CloseBookingRequest }
     * 
     */
    public CloseBookingRequest createCloseBookingRequest() {
        return new CloseBookingRequest();
    }

    /**
     * Create an instance of {@link GetDoctorsBySpecializationResponse }
     * 
     */
    public GetDoctorsBySpecializationResponse createGetDoctorsBySpecializationResponse() {
        return new GetDoctorsBySpecializationResponse();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

}
